import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/components/parts/Providers';
import LayoutClient from '@/components/parts/LayoutClient';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Todolist App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: any) => (
  <html lang="en">
    <body className={inter.className}>
      <Providers>
        {children}

        <LayoutClient />
      </Providers>
    </body>
  </html>
);

export default RootLayout;
